@extends('layouts.app')

@section('content')
<div class="space-y-6">
    <!-- Breadcrumb -->
    <nav class="flex" aria-label="Breadcrumb">
        <ol class="inline-flex items-center space-x-1 md:space-x-3">
            <li>
                <a href="{{ route('dashboard') }}" class="text-gray-700 hover:text-blue-600">
                    Home
                </a>
            </li>
            <li>
                <div class="flex items-center">
                    <svg class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                        <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path>
                    </svg>
                    <a href="{{ route('videos.index') }}" class="ml-1 text-gray-700 hover:text-blue-600">
                        Videos
                    </a>
                </div>
            </li>
            <li aria-current="page">
                <div class="flex items-center">
                    <svg class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                        <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path>
                    </svg>
                    <span class="ml-1 text-gray-500">{{ $video['title'] }}</span>
                </div>
            </li>
        </ol>
    </nav>

    <!-- Main Content -->
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <!-- Video Details (Left Column) -->
        <div class="lg:col-span-2 space-y-6">
            <!-- Video Thumbnail -->
            <div class="bg-white rounded-lg shadow-sm overflow-hidden">
                @if(!empty($video['thumbnail_url']))
                    <img 
                        src="{{ $video['thumbnail_url'] }}" 
                        alt="{{ $video['title'] }}"
                        class="w-full h-96 object-cover"
                    >
                @else
                    <div class="w-full h-96 bg-gray-200 flex items-center justify-center">
                        <svg class="h-24 w-24 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z"></path>
                        </svg>
                    </div>
                @endif

                <!-- Audio Preview Player -->
                @if($audioUrl)
                    <div class="p-6 bg-gray-50 border-t">
                        <div class="flex items-center space-x-3 mb-2">
                            <svg class="h-5 w-5 text-green-600" fill="currentColor" viewBox="0 0 20 20">
                                <path d="M18 3a1 1 0 00-1.196-.98l-10 2A1 1 0 006 5v9.114A4.369 4.369 0 005 14c-1.657 0-3 .895-3 2s1.343 2 3 2 3-.895 3-2V7.82l8-1.6v5.894A4.37 4.37 0 0015 12c-1.657 0-3 .895-3 2s1.343 2 3 2 3-.895 3-2V3z"></path>
                            </svg>
                            <h3 class="text-lg font-heading font-medium text-gray-900">Audio Preview</h3>
                        </div>
                        <audio controls class="w-full">
                            <source src="{{ $audioUrl }}" type="audio/mpeg">
                            Your browser does not support the audio element.
                        </audio>
                        <p class="mt-2 text-xs text-gray-500">
                            Preview generated by AI • Link expires in 1 hour
                        </p>
                    </div>
                @endif
            </div>

            <!-- Video Information -->
            <div class="bg-white rounded-lg shadow-sm p-6">
                <h1 class="text-3xl font-heading font-bold text-gray-900 mb-4">
                    {{ $video['title'] }}
                </h1>

                <!-- Meta Info -->
                <div class="flex flex-wrap gap-4 mb-6 text-sm text-gray-600">
                    @if(!empty($video['instructor']))
                        <div class="flex items-center">
                            <svg class="h-5 w-5 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path>
                            </svg>
                            {{ $video['instructor'] }}
                        </div>
                    @endif

                    @if(!empty($video['duration']))
                        <div class="flex items-center">
                            <svg class="h-5 w-5 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                            </svg>
                            {{ $video['duration'] }}
                        </div>
                    @endif

                    @if(!empty($video['difficulty']))
                        <div class="flex items-center">
                            <svg class="h-5 w-5 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path>
                            </svg>
                            {{ $video['difficulty'] }}
                        </div>
                    @endif

                    @if(!empty($video['category']))
                        <div>
                            <span class="inline-flex items-center px-3 py-1 rounded-full text-sm font-medium bg-blue-100 text-blue-800">
                                {{ $video['category'] }}
                            </span>
                        </div>
                    @endif
                </div>

                <!-- Description -->
                @if(!empty($video['description']))
                    <div class="prose max-w-none">
                        <h3 class="text-lg font-heading font-medium text-gray-900 mb-2">Description</h3>
                        <p class="text-gray-700">{{ $video['description'] }}</p>
                    </div>
                @endif

                <!-- Additional Details -->
                <div class="mt-6 border-t pt-6">
                    <dl class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        @if(!empty($video['id']))
                            <div>
                                <dt class="text-sm font-medium text-gray-500">Video ID</dt>
                                <dd class="mt-1 text-sm text-gray-900">{{ $video['id'] }}</dd>
                            </div>
                        @endif

                        @if(!empty($video['created_at']))
                            <div>
                                <dt class="text-sm font-medium text-gray-500">Created</dt>
                                <dd class="mt-1 text-sm text-gray-900">{{ date('M d, Y', strtotime($video['created_at'])) }}</dd>
                            </div>
                        @endif

                        @if(!empty($video['jwplayer_id']))
                            <div>
                                <dt class="text-sm font-medium text-gray-500">JW Player ID</dt>
                                <dd class="mt-1 text-sm text-gray-900 font-mono text-xs">{{ $video['jwplayer_id'] }}</dd>
                            </div>
                        @endif
                    </dl>
                </div>
            </div>
        </div>

        <!-- Sidebar (Right Column) -->
        <div class="space-y-6">
            <!-- Actions -->
            <div class="bg-white rounded-lg shadow-sm p-6">
                <h3 class="text-lg font-heading font-medium text-gray-900 mb-4">Actions</h3>
                <div class="space-y-3">
                    <a href="{{ route('videos.index') }}" class="block w-full text-center btn-secondary">
                        ← Back to Library
                    </a>
                </div>
            </div>

            <!-- Related Videos -->
            @if(!empty($relatedVideos) && count($relatedVideos) > 0)
                <div class="bg-white rounded-lg shadow-sm p-6">
                    <h3 class="text-lg font-heading font-medium text-gray-900 mb-4">Related Videos</h3>
                    <div class="space-y-4">
                        @foreach($relatedVideos as $related)
                            <a href="{{ route('videos.show', $related['id']) }}" class="block group">
                                <div class="flex space-x-3">
                                    @if(!empty($related['thumbnail_url']))
                                        <img 
                                            src="{{ $related['thumbnail_url'] }}" 
                                            alt="{{ $related['title'] }}"
                                            class="w-24 h-16 object-cover rounded"
                                        >
                                    @else
                                        <div class="w-24 h-16 bg-gray-200 rounded flex items-center justify-center flex-shrink-0">
                                            <svg class="h-6 w-6 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z"></path>
                                            </svg>
                                        </div>
                                    @endif
                                    <div class="flex-1 min-w-0">
                                        <p class="text-sm font-medium text-gray-900 group-hover:text-blue-600 line-clamp-2">
                                            {{ $related['title'] }}
                                        </p>
                                        <p class="text-xs text-gray-500 mt-1">
                                            {{ $related['instructor'] ?? 'Unknown' }}
                                        </p>
                                    </div>
                                </div>
                            </a>
                        @endforeach
                    </div>
                </div>
            @endif
        </div>
    </div>
</div>
@endsection


